In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../files/survey_results_public.csv')

In [5]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'Age', 'Age1stCode', 'CompFreq',
       'CompTotal', 'ConvertedComp', 'Country', 'CurrencyDesc',
       'CurrencySymbol', 'DatabaseDesireNextYear', 'DatabaseWorkedWith',
       'DevType', 'EdLevel', 'Employment', 'Ethnicity', 'Gender', 'JobFactors',
       'JobSat', 'JobSeek', 'LanguageDesireNextYear', 'LanguageWorkedWith',
       'MiscTechDesireNextYear', 'MiscTechWorkedWith',
       'NEWCollabToolsDesireNextYear', 'NEWCollabToolsWorkedWith', 'NEWDevOps',
       'NEWDevOpsImpt', 'NEWEdImpt', 'NEWJobHunt', 'NEWJobHuntResearch',
       'NEWLearn', 'NEWOffTopic', 'NEWOnboardGood', 'NEWOtherComms',
       'NEWOvertime', 'NEWPurchaseResearch', 'NEWPurpleLink', 'NEWSOSites',
       'NEWStuck', 'OpSys', 'OrgSize', 'PlatformDesireNextYear',
       'PlatformWorkedWith', 'PurchaseWhat', 'Sexuality', 'SOAccount',
       'SOComm', 'SOPartFreq', 'SOVisitFreq', 'SurveyEase', 'SurveyLength',
       'Trans', 'UndergradMajor', 'WebframeDesireNextYear',
       'WebframeWorkedWith', 'WelcomeChange', 'WorkWeekHrs', 'YearsCode',
       'YearsCodePro'],
      dtype='object')

In [6]:
df["Country"]

0                   Germany
1            United Kingdom
2        Russian Federation
3                   Albania
4             United States
                ...
64456         United States
64457               Morocco
64458              Viet Nam
64459                Poland
64460                 Spain
Name: Country, Length: 64461, dtype: object

In [7]:
df["Age"].value_counts()

Age
25.0    2693
28.0    2412
30.0    2406
26.0    2391
27.0    2338
        ...
88.0       1
16.5       1
23.4       1
95.0       1
14.5       1
Name: count, Length: 110, dtype: int64

In [8]:
df.loc[0]

Respondent                                                  1
MainBranch                     I am a developer by profession
Hobbyist                                                  Yes
Age                                                       NaN
Age1stCode                                                 13
                                       ...
WebframeWorkedWith                       ASP.NET;ASP.NET Core
WelcomeChange         Just as welcome now as I felt last year
WorkWeekHrs                                              50.0
YearsCode                                                  36
YearsCodePro                                               27
Name: 0, Length: 61, dtype: object

In [9]:
df.loc[0, "Country"]

'Germany'

In [12]:
# df.loc[[0,5,1200], "Country"]
# df.loc[0:10, ["Country", "Age"]]  # slicing rows and columns
df.loc[0:10, "Age":"Country"]

     Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country
0    NaN         13  Monthly        NaN            NaN             Germany
1    NaN         19      NaN        NaN            NaN      United Kingdom
2    NaN         15      NaN        NaN            NaN  Russian Federation
3   25.0         18      NaN        NaN            NaN             Albania
4   31.0         16      NaN        NaN            NaN       United States
5    NaN         14      NaN        NaN            NaN             Germany
6    NaN         18  Monthly        NaN            NaN               India
7   36.0         12   Yearly   116000.0       116000.0       United States
8   30.0         20      NaN        NaN            NaN             Tunisia
9   22.0         14   Yearly    25000.0        32315.0      United Kingdom
10  23.0         13   Yearly    31000.0        40070.0      United Kingdom

In [14]:
df.iloc[0:5]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
1,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
2,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
3,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
4,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [17]:
df["YearsCodePro"] = pd.to_numeric(df["YearsCodePro"], errors='coerce')
df[df["YearsCodePro"] > 10]

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
0,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27.0
7,8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13.0
12,13,"I am not primarily a developer, but I write co...",Yes,53.0,14,Monthly,3000.0,38916.0,Netherlands,European Euro,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20.0
15,16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23.0
17,18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64376,51773,NaN,Yes,NaN,18,NaN,NaN,NaN,Bangladesh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,18.0
64392,55074,NaN,Yes,36.0,35,NaN,NaN,NaN,Bangladesh,NaN,...,Easy,Appropriate in length,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,A lot less welcome now than last year,NaN,Less than 1 year,12.0
64407,57084,NaN,Yes,NaN,18,NaN,NaN,NaN,Sweden,NaN,...,NaN,NaN,NaN,"A social science (such as anthropology, psycho...",Django;jQuery,Django;jQuery,Just as welcome now as I felt last year,NaN,12,15.0
64415,58819,NaN,Yes,NaN,11,NaN,NaN,NaN,Myanmar,NaN,...,Easy,Too short,NaN,NaN,NaN,ASP.NET,NaN,NaN,5,29.0
64427,60149,NaN,Yes,34.0,18,NaN,NaN,NaN,Brazil,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django,Just as welcome now as I felt last year,NaN,16,14.0

In [19]:
df.query('YearsCodePro > 15 and WebframeWorkedWith.str.contains("Vue", na=False)')

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
40,41,I am a developer by profession,No,NaN,15,Yearly,106000.0,106000.0,United States,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",Vue.js,ASP.NET;Vue.js,A lot less welcome now than last year,40.0,25,20.0
212,214,I am a developer by profession,Yes,41.0,16,Yearly,160000.0,160000.0,United States,United States dollar,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Vue.js,ASP.NET;ASP.NET Core;jQuery;Vue.js,Just as welcome now as I felt last year,40.0,25,19.0
221,223,I am a developer by profession,Yes,44.0,10,Monthly,4500.0,58368.0,Portugal,European Euro,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET Core;React.js;Vue.js,ASP.NET Core;React.js;Vue.js,A lot more welcome now than last year,37.0,30,20.0
305,307,I am a developer by profession,Yes,41.0,14,Monthly,50000.0,648588.0,Ireland,European Euro,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",Angular;Express;Laravel;Vue.js,Angular;Express;Laravel;Vue.js,Just as welcome now as I felt last year,45.0,24,19.0
313,315,I am a developer by profession,Yes,46.0,8,Yearly,160000.0,160000.0,United States,United States dollar,...,Easy,Too short,No,NaN,Vue.js,Laravel;Vue.js,Just as welcome now as I felt last year,35.0,20,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64013,65476,I am a developer by profession,Yes,NaN,9,Yearly,200000.0,200000.0,United States,United States dollar,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",Angular;Flask;Vue.js,Angular;Flask;React.js;Vue.js,NaN,40.0,43,30.0
64096,65567,I am a developer by profession,Yes,NaN,12,NaN,NaN,NaN,United States,United States dollar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;Express;Vue.js,ASP.NET;React.js;Vue.js,NaN,43.0,28,20.0
64121,65595,I am a developer by profession,Yes,NaN,20,Yearly,27170564.0,369.0,"Venezuela, Bolivarian Republic of...",Venezuelan bolivar,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",Angular.js;Django;jQuery;Laravel;React.js;Vue.js,jQuery;Laravel;Vue.js,A lot more welcome now than last year,63.0,29,27.0
64230,18748,NaN,Yes,NaN,30,NaN,NaN,NaN,Iran,NaN,...,Easy,Too short,Yes,Web development or web design,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,A lot less welcome now than last year,NaN,30,30.0
64279,31525,NaN,Yes,67.0,35,NaN,NaN,NaN,United Kingdom,NaN,...,Easy,Appropriate in length,No,Fine arts or performing arts (such as graphic ...,Vue.js,Vue.js,Somewhat less welcome now than last year,NaN,35,22.0